name: Sync Backend to Hugging Face Spaces

on:
  push:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face  
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: "luciesp"
          HF_SPACE_NAME: "auravoice-backend"
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          cd backend
          
          # Initialisation
          git init
          git checkout -b main
          
          # --- ACTIVATION DE LFS (C'est ça qui manquait !) ---
          git lfs install
          git lfs track "*.keras"
          git lfs track "*.pkl"
          git add .gitattributes
          # ---------------------------------------------------
          
          git add .
          git commit -m "Deploy with LFS support"
          
          # Push forcé
          git push --force https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$HF_SPACE_NAME main
